version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
      MYSQL_USER: min33sky
      MYSQL_PASSWORD: qweqwe123
    restart: always
